// <auto-generated />
using System;
using Ferreto.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ferreto.Migrations
{
    [DbContext(typeof(FerretoSContext))]
    [Migration("20200617022753_ModifykeystotableDetalle")]
    partial class ModifykeystotableDetalle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ferreto.Models.Acceso", b =>
                {
                    b.Property<int>("Idacceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idacceso")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("bit");

                    b.Property<string>("Formulario")
                        .HasColumnName("formulario")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Idacceso")
                        .HasName("PK__Acceso__F7B9EC7108DF438A");

                    b.ToTable("Acceso");
                });

            modelBuilder.Entity("Ferreto.Models.Categoria", b =>
                {
                    b.Property<int>("Idcategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idcategoria")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Idcategoria")
                        .HasName("PK__Categori__140587C70FF55C1E");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Ferreto.Models.Compra", b =>
                {
                    b.Property<int>("Idcompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idcompra")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Codproveedor")
                        .HasColumnName("codproveedor")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fechacompra")
                        .HasColumnName("fechacompra")
                        .HasColumnType("date");

                    b.Property<int>("Idusuario")
                        .HasColumnName("idusuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Totalcompra")
                        .HasColumnName("totalcompra")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Idcompra")
                        .HasName("PK__Compra__81E11FE364F2179A");

                    b.HasIndex("Codproveedor");

                    b.HasIndex("Idusuario");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("Ferreto.Models.Detallecompra", b =>
                {
                    b.Property<int>("Iddetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("iddetalle")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnName("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Idcompra")
                        .HasColumnName("idcompra")
                        .HasColumnType("int");

                    b.Property<int>("Idproducto")
                        .HasColumnName("idproducto")
                        .HasColumnType("int");

                    b.Property<double>("Preciocompra")
                        .HasColumnName("preciocompra")
                        .HasColumnType("float");

                    b.HasKey("Iddetalle")
                        .HasName("PK__Detallec__6FE8F71F8D9D731F");

                    b.HasIndex("Idcompra");

                    b.HasIndex("Idproducto");

                    b.ToTable("Detallecompra");
                });

            modelBuilder.Entity("Ferreto.Models.Detallefactura", b =>
                {
                    b.Property<int>("Iddetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("iddetalle")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cantidad")
                        .HasColumnName("cantidad")
                        .HasColumnType("float");

                    b.Property<int>("Idfactura")
                        .HasColumnName("idfactura")
                        .HasColumnType("int");

                    b.Property<int>("Idproducto")
                        .HasColumnName("idproducto")
                        .HasColumnType("int");

                    b.Property<double>("Precioventa")
                        .HasColumnName("precioventa")
                        .HasColumnType("float");

                    b.HasKey("Iddetalle")
                        .HasName("PK__Venta__F82D1AFBC027FC2F");

                    b.HasIndex("Idfactura");

                    b.HasIndex("Idproducto");

                    b.ToTable("Detallefactura");
                });

            modelBuilder.Entity("Ferreto.Models.Factura", b =>
                {
                    b.Property<int>("Idfactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idfactura")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fechafacturacion")
                        .HasColumnType("date");

                    b.Property<int>("Idusuario")
                        .HasColumnName("idusuario")
                        .HasColumnType("int");

                    b.Property<double>("Iva")
                        .HasColumnName("iva")
                        .HasColumnType("float");

                    b.Property<string>("Nserie")
                        .IsRequired()
                        .HasColumnName("nserie")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<decimal>("Totalmasiva")
                        .HasColumnName("totalmasiva")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("Totalsiniva")
                        .HasColumnName("totalsiniva")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Idfactura")
                        .HasName("PK__Factura__40FF55D87469121A");

                    b.HasIndex("Idusuario");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("Ferreto.Models.Inventario", b =>
                {
                    b.Property<int>("Idinventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idinventario")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Existencia")
                        .HasColumnName("existencia")
                        .HasColumnType("int");

                    b.Property<int>("Idproducto")
                        .HasColumnName("idproducto")
                        .HasColumnType("int");

                    b.Property<string>("Nombreproducto")
                        .IsRequired()
                        .HasColumnName("nombreproducto")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<decimal>("Unidademonetarias")
                        .HasColumnName("unidademonetarias")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Idinventario")
                        .HasName("PK__Inventar__4D2829C521F4387F");

                    b.HasIndex("Idproducto");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("Ferreto.Models.Marca", b =>
                {
                    b.Property<int>("Idmarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idmarca")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Idmarca")
                        .HasName("PK__Marca__6D3757B2245E37C0");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("Ferreto.Models.Movinventario", b =>
                {
                    b.Property<int>("Idmovinventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idmovinventario")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Idinventario")
                        .HasColumnName("idinventario")
                        .HasColumnType("int");

                    b.Property<int>("Idproducto")
                        .HasColumnName("idproducto")
                        .HasColumnType("int");

                    b.Property<int>("Movimientonumero")
                        .HasColumnName("movimientonumero")
                        .HasColumnType("int");

                    b.Property<int?>("Tipomovimiento")
                        .HasColumnName("tipomovimiento")
                        .HasColumnType("int");

                    b.HasKey("Idmovinventario")
                        .HasName("PK__Movinven__0823AA9AD07451B9");

                    b.HasIndex("Idinventario");

                    b.HasIndex("Idproducto");

                    b.ToTable("Movinventario");
                });

            modelBuilder.Entity("Ferreto.Models.Persona", b =>
                {
                    b.Property<int>("Idpersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idpersona")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnName("apellido")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Cedula")
                        .HasColumnName("cedula")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnName("direccion")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Telefono")
                        .HasColumnName("telefono")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.HasKey("Idpersona")
                        .HasName("PK__Persona__5C5C1E2883604904");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("Ferreto.Models.Precioproducto", b =>
                {
                    b.Property<int>("Idprecio")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idprecio")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Fechacreacion")
                        .HasColumnName("fechacreacion")
                        .HasColumnType("date");

                    b.Property<int>("Idproducto")
                        .HasColumnName("idproducto")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnName("precio")
                        .HasColumnType("float");

                    b.HasKey("Idprecio")
                        .HasName("PK__Preciopr__7FFE066BD73D1BB6");

                    b.HasIndex("Idproducto");

                    b.ToTable("Precioproducto");
                });

            modelBuilder.Entity("Ferreto.Models.Presentacion", b =>
                {
                    b.Property<int>("Idpresentacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idpresentacion")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Peso")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Tamaño")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Idpresentacion")
                        .HasName("PK__Presenta__FF41A0F79D5415C0");

                    b.ToTable("Presentacion");
                });

            modelBuilder.Entity("Ferreto.Models.Producto", b =>
                {
                    b.Property<int>("Idproducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idproducto")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codproducto")
                        .IsRequired()
                        .HasColumnName("codproducto")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<bool>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fproduccion")
                        .HasColumnName("fproduccion")
                        .HasColumnType("date");

                    b.Property<DateTime>("Fvencimiento")
                        .HasColumnName("fvencimiento")
                        .HasColumnType("date");

                    b.Property<int>("Idcategoria")
                        .HasColumnName("idcategoria")
                        .HasColumnType("int");

                    b.Property<int>("Idmarca")
                        .HasColumnName("idmarca")
                        .HasColumnType("int");

                    b.Property<int>("Idpresentacion")
                        .HasColumnName("idpresentacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Ubicacion")
                        .HasColumnName("ubicacion")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Idproducto")
                        .HasName("PK__Producto__DC53BE3C52DBC22F");

                    b.HasIndex("Idcategoria");

                    b.HasIndex("Idmarca");

                    b.HasIndex("Idpresentacion");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Ferreto.Models.Proveedores", b =>
                {
                    b.Property<int>("Idproveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idproveedor")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnName("empresa")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("bit");

                    b.Property<int>("Idpersona")
                        .HasColumnName("idpersona")
                        .HasColumnType("int");

                    b.HasKey("Idproveedor")
                        .HasName("PK__Proveedo__2DCD485D425146B8");

                    b.HasIndex("Idpersona");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Ferreto.Models.Rol", b =>
                {
                    b.Property<int>("Idrol")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idrol")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<bool>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombrerol")
                        .IsRequired()
                        .HasColumnName("nombrerol")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Idrol")
                        .HasName("PK__Rol__24C6BB20881A1796");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Ferreto.Models.Rolacceso", b =>
                {
                    b.Property<int>("Idrolacceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idrolacceso")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Idacceso")
                        .HasColumnName("idacceso")
                        .HasColumnType("int");

                    b.Property<int>("Idrol")
                        .HasColumnName("idrol")
                        .HasColumnType("int");

                    b.HasKey("Idrolacceso")
                        .HasName("PK__Rolacces__C6C1FA005A3C3313");

                    b.HasIndex("Idacceso");

                    b.HasIndex("Idrol");

                    b.ToTable("Rolacceso");
                });

            modelBuilder.Entity("Ferreto.Models.Rolusuario", b =>
                {
                    b.Property<int>("Idrolusuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idrolusuario")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("bit");

                    b.Property<int>("Idrol")
                        .HasColumnName("idrol")
                        .HasColumnType("int");

                    b.Property<int>("Idusuario")
                        .HasColumnName("idusuario")
                        .HasColumnType("int");

                    b.HasKey("Idrolusuario")
                        .HasName("PK__Rolusuar__72B1041BD51414B6");

                    b.HasIndex("Idrol");

                    b.HasIndex("Idusuario");

                    b.ToTable("Rolusuario");
                });

            modelBuilder.Entity("Ferreto.Models.Usuario", b =>
                {
                    b.Property<int>("Idusuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idusuario")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("bit");

                    b.Property<int>("Idpersona")
                        .HasColumnName("idpersona")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnName("login")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Idusuario")
                        .HasName("PK__Usuario__080A97438E4C1E6C");

                    b.HasIndex("Idpersona");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Ferreto.Models.Compra", b =>
                {
                    b.HasOne("Ferreto.Models.Proveedores", "CodproveedorNavigation")
                        .WithMany("Compra")
                        .HasForeignKey("Codproveedor")
                        .HasConstraintName("fk_p")
                        .IsRequired();

                    b.HasOne("Ferreto.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Compra")
                        .HasForeignKey("Idusuario")
                        .HasConstraintName("fk_u")
                        .IsRequired();
                });

            modelBuilder.Entity("Ferreto.Models.Detallecompra", b =>
                {
                    b.HasOne("Ferreto.Models.Compra", "IdcompraNavigation")
                        .WithMany("Detallecompra")
                        .HasForeignKey("Idcompra")
                        .HasConstraintName("fk_compra")
                        .IsRequired();

                    b.HasOne("Ferreto.Models.Producto", "IdproductoNavigation")
                        .WithMany("Detallecompra")
                        .HasForeignKey("Idproducto")
                        .HasConstraintName("fk_producto")
                        .IsRequired();
                });

            modelBuilder.Entity("Ferreto.Models.Detallefactura", b =>
                {
                    b.HasOne("Ferreto.Models.Factura", "IdfacturaNavigation")
                        .WithMany("Detallefacturas")
                        .HasForeignKey("Idfactura")
                        .HasConstraintName("fk_tfactura")
                        .IsRequired();

                    b.HasOne("Ferreto.Models.Producto", "IdproductoNavigation")
                        .WithMany("Detallefactura")
                        .HasForeignKey("Idproducto")
                        .HasConstraintName("fk_pr")
                        .IsRequired();
                });

            modelBuilder.Entity("Ferreto.Models.Factura", b =>
                {
                    b.HasOne("Ferreto.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Factura")
                        .HasForeignKey("Idusuario")
                        .HasConstraintName("fk_Usua")
                        .IsRequired();
                });

            modelBuilder.Entity("Ferreto.Models.Inventario", b =>
                {
                    b.HasOne("Ferreto.Models.Producto", "IdproductoNavigation")
                        .WithMany("Inventario")
                        .HasForeignKey("Idproducto")
                        .HasConstraintName("fk_pro")
                        .IsRequired();
                });

            modelBuilder.Entity("Ferreto.Models.Movinventario", b =>
                {
                    b.HasOne("Ferreto.Models.Inventario", "IdinventarioNavigation")
                        .WithMany("Movinventario")
                        .HasForeignKey("Idinventario")
                        .HasConstraintName("fk_tinventario")
                        .IsRequired();

                    b.HasOne("Ferreto.Models.Producto", "IdproductoNavigation")
                        .WithMany("Movinventario")
                        .HasForeignKey("Idproducto")
                        .HasConstraintName("fk_tproductos")
                        .IsRequired();
                });

            modelBuilder.Entity("Ferreto.Models.Precioproducto", b =>
                {
                    b.HasOne("Ferreto.Models.Producto", "IdproductoNavigation")
                        .WithMany("Precioproducto")
                        .HasForeignKey("Idproducto")
                        .HasConstraintName("fk_tproducts")
                        .IsRequired();
                });

            modelBuilder.Entity("Ferreto.Models.Producto", b =>
                {
                    b.HasOne("Ferreto.Models.Categoria", "IdcategoriaNavigation")
                        .WithMany("Producto")
                        .HasForeignKey("Idcategoria")
                        .HasConstraintName("fk_categoria")
                        .IsRequired();

                    b.HasOne("Ferreto.Models.Marca", "IdmarcaNavigation")
                        .WithMany("Producto")
                        .HasForeignKey("Idmarca")
                        .HasConstraintName("fk_marca")
                        .IsRequired();

                    b.HasOne("Ferreto.Models.Presentacion", "IdpresentacionNavigation")
                        .WithMany("Producto")
                        .HasForeignKey("Idpresentacion")
                        .HasConstraintName("fk_presentacion")
                        .IsRequired();
                });

            modelBuilder.Entity("Ferreto.Models.Proveedores", b =>
                {
                    b.HasOne("Ferreto.Models.Persona", "IdpersonaNavigation")
                        .WithMany("Proveedores")
                        .HasForeignKey("Idpersona")
                        .HasConstraintName("fk_person")
                        .IsRequired();
                });

            modelBuilder.Entity("Ferreto.Models.Rolacceso", b =>
                {
                    b.HasOne("Ferreto.Models.Acceso", "IdaccesoNavigation")
                        .WithMany("Rolacceso")
                        .HasForeignKey("Idacceso")
                        .HasConstraintName("fk_Acceso")
                        .IsRequired();

                    b.HasOne("Ferreto.Models.Rol", "IdrolNavigation")
                        .WithMany("Rolacceso")
                        .HasForeignKey("Idrol")
                        .HasConstraintName("fk_tRol")
                        .IsRequired();
                });

            modelBuilder.Entity("Ferreto.Models.Rolusuario", b =>
                {
                    b.HasOne("Ferreto.Models.Rol", "IdrolNavigation")
                        .WithMany("Rolusuario")
                        .HasForeignKey("Idrol")
                        .HasConstraintName("fk_rol")
                        .IsRequired();

                    b.HasOne("Ferreto.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Rolusuario")
                        .HasForeignKey("Idusuario")
                        .HasConstraintName("fk_tusuario")
                        .IsRequired();
                });

            modelBuilder.Entity("Ferreto.Models.Usuario", b =>
                {
                    b.HasOne("Ferreto.Models.Persona", "IdpersonaNavigation")
                        .WithMany("Usuario")
                        .HasForeignKey("Idpersona")
                        .HasConstraintName("fk_pers")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
